import type { OfferingMeta } from "./offerings.js";

/** Stub SKUs migrated from legacy static catalog (seed source). */
export const OFFERING_STUB_CATALOG: Record<string, OfferingMeta> = {
  "agile-readiness": {
    code: "agile-readiness",
    title: "Agile Readiness Program",
    kind: "course",
    category: "training",
    scheduleBound: true,
    examAccess: "preview_only",
    safeOrgPaymentEligible: false,
    defaultUnitPrice: "299.00",
    currency: "USD",
    roleTags: ["learner", "scrum_master", "product_owner"],
    deliveryMode: "live",
    upcomingBatchId: "batch-agile-readiness-q3",
  },
  "course-agile-fundamentals": {
    code: "course-agile-fundamentals",
    title: "Agile Fundamentals (Cohort)",
    kind: "course",
    category: "training",
    scheduleBound: true,
    examAccess: "preview_only",
    safeOrgPaymentEligible: false,
    defaultUnitPrice: "299.00",
    currency: "USD",
    roleTags: ["learner", "scrum_master"],
    deliveryMode: "live",
    upcomingBatchId: "cohort-2026-q3",
  },
  "exam-practice-free": {
    code: "exam-practice-free",
    title: "Free Practice Exam",
    kind: "exam",
    category: "certification",
    scheduleBound: false,
    examAccess: "free",
    safeOrgPaymentEligible: false,
    defaultUnitPrice: "0.00",
    currency: "USD",
    roleTags: ["learner"],
    certBody: "scrum.org",
    deliveryMode: "self_paced",
  },
  "exam-mock-certification": {
    code: "exam-mock-certification",
    title: "Mock Certification Exam",
    kind: "certification_mock",
    category: "certification",
    scheduleBound: false,
    examAccess: "paid",
    safeOrgPaymentEligible: false,
    defaultUnitPrice: "49.00",
    currency: "USD",
    roleTags: ["learner"],
    certBody: "scrum.org",
    deliveryMode: "self_paced",
  },
  "safe-leading-safe": {
    code: "safe-leading-safe",
    title: "SAFe Leading SAFe",
    kind: "course",
    category: "certification",
    scheduleBound: true,
    examAccess: "preview_only",
    safeOrgPaymentEligible: true,
    defaultUnitPrice: "999.00",
    currency: "USD",
    roleTags: ["learner", "safe_program_consultant"],
    certBody: "scaled agile",
    deliveryMode: "live",
    upcomingBatchId: "safe-leading-q3",
  },
  "service-mock-interview-sm": {
    code: "service-mock-interview-sm",
    title: "Scrum Master Mock Interview",
    kind: "service",
    category: "service",
    scheduleBound: true,
    examAccess: "preview_only",
    safeOrgPaymentEligible: false,
    defaultUnitPrice: "79.00",
    currency: "USD",
    roleTags: ["scrum_master"],
    deliveryMode: "live",
    upcomingBatchId: "mock-sm-slots",
  },
};

export function listStubOfferings(): OfferingMeta[] {
  return Object.values(OFFERING_STUB_CATALOG);
}
